- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: name-tests-test
      args: ["--django"]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: "v4.3.21"
  hooks:
    - id: isort
      entry: isort -rc
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.7
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
    - id: flake8
      args: [--max-line-length=100]
- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: [-l, --recursive, -x, tests]
      files: .py$
